# Generated by Django 3.1 on 2020-10-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_following',
            new_name='user_followed',
        ),
    ]
