# Generated by Django 3.1 on 2020-10-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201026_0956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'user_followed')},
        ),
    ]
