# Generated by Django 3.1 on 2020-10-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201026_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['emoji_type'], 'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
