# Generated by Django 3.1 on 2020-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201027_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterField(
            model_name='like',
            name='emoji_type',
            field=models.CharField(choices=[('1-like', '<i class="em em---1" aria-role="presentation" aria-label="THUMBS UP SIGN"></i>'), ('dislike', '<i class="em em--1" aria-role="presentation" aria-label="THUMBS DOWN SIGN"></i>'), ('smile', '<i class="em em-smile" aria-role="presentation" aria-label="SMILING FACE WITH OPEN MOUTH AND SMILING EYES"></i>'), ('heart', '<i class="em em-heart" aria-role="presentation" aria-label="HEAVY BLACK HEART"></i>'), ('thanks', '<i class="em em-bouquet" aria-role="presentation" aria-label="BOUQUET"></i>')], default='1-like', max_length=10),
        ),
    ]
