# Generated by Django 3.1 on 2020-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201027_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['emoji_type'], 'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterField(
            model_name='like',
            name='emoji_type',
            field=models.CharField(choices=[(1, 'like'), (2, 'dislike'), (3, 'smile'), (4, 'heart'), (5, 'thanks')], default=1, max_length=10),
        ),
    ]
