# Generated by Django 3.1 on 2020-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201027_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='emoji_type',
            field=models.IntegerField(choices=[(1, 'like'), (2, 'dislike'), (3, 'smile'), (4, 'heart'), (5, 'thanks')], default=1),
        ),
    ]
