# Generated by Django 3.1 on 2020-10-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201027_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment')},
        ),
    ]
