# Generated by Django 3.1 on 2020-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20201210_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, default='https://s3.amazonaws.com/37assets/svn/765-default-avatar.png', max_length=4000),
        ),
    ]
