# Generated by Django 3.1 on 2020-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201022_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='emoji_type',
            field=models.CharField(choices=[('like', '<i class="em em---1" aria-role="presentation" aria-label="THUMBS UP SIGN"></i>'), ('dislike', '<i class="em em--1" aria-role="presentation" aria-label="THUMBS DOWN SIGN"></i>'), ('smile', '<i class="em em-smile" aria-role="presentation" aria-label="SMILING FACE WITH OPEN MOUTH AND SMILING EYES"></i>'), ('heart', '<i class="em em-heart" aria-role="presentation" aria-label="HEAVY BLACK HEART"></i>'), ('thanks', '<i class="em em-bouquet" aria-role="presentation" aria-label="BOUQUET"></i>')], default='like', max_length=10),
        ),
    ]
