name: Testing Network app
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          DJANGO_SETTINGS_MODULE: project4.settings.dev
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Django tests
        run: |
            python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: project4.settings.dev