name: Testing Network app
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: nanasess/setup-chromedriver@master
      #   with:
          # Optional: do not specify to match Chrome's version
      #     chromedriver-version: '77.0.3865.40'
      # - run: |
      #     export DISPLAY=:99
      #     chromedriver --url-base=/wd/hub &
      #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Django tests
        run: |
            python manage.py test